import Head from 'next/head';
import Image from 'next/image';
import requests from '../api/requests';
import Header from '../components/Header';
import Nav from '../components/Nav';
import tmdb from '../public/tmdb.svg';

export default function Home({ results }) {
  console.log(results);

  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <div className="flex justify-center">
        <Image
          className="object-contain"
          height={100}
          width={100}
          src={tmdb}
          alt="tmdb"
        />
      </div>
    </div>
  )
}

// Server-side render - executed before the page is loaded
export async function getServerSideProps(context) {
  // The context is a rich object containing details about the current request, url etc.
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
